version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
